package inspector

import "fmt"

// GenerateHints returns actionable suggestions for the given failure code.
// certInfo may be nil (e.g., when no cert was presented).
func GenerateHints(code FailureCode, certInfo *CertInfo, trustedCA string) []string {
	switch code {
	case FailureNoCert:
		return noCertHints()
	case FailureWrongCA:
		return wrongCAHints(certInfo, trustedCA)
	case FailureExpired:
		return expiredHints(certInfo)
	case FailureNotYetValid:
		return notYetValidHints(certInfo)
	case FailureWeakKey:
		return weakKeyHints(certInfo)
	case FailureNoClientAuth:
		return noClientAuthHints()
	case FailureNoServerAuth:
		return noServerAuthHints()
	default:
		return nil
	}
}

func noCertHints() []string {
	return []string{
		"Your client did not present a certificate during the TLS handshake.",
		"If using curl, add: --cert client.crt --key client.key --cacert ca.crt",
		"If using nginx, set: proxy_ssl_certificate /path/to/client.crt; and proxy_ssl_certificate_key /path/to/client.key;",
		"If using Envoy, set transport_socket.typed_config.common_tls_context.tls_certificates in the cluster config.",
		"If using Spring/Java, configure javax.net.ssl.keyStore and javax.net.ssl.keyStorePassword system properties.",
		"If using Node.js, pass { cert, key, ca } options to https.Agent or tls.connect.",
	}
}

func wrongCAHints(certInfo *CertInfo, trustedCA string) []string {
	hints := []string{
		fmt.Sprintf("Your certificate was signed by %q, but this server trusts only %q.", certInfo.Issuer, trustedCA),
		"Make sure you are using the client.crt and client.key files generated by this sandbox.",
		"If you brought your own CA, ensure the server was started with MTLS_TLS_CA_CERT pointing to the same CA that signed your client certificate.",
	}
	return hints
}

func expiredHints(certInfo *CertInfo) []string {
	return []string{
		fmt.Sprintf("Your certificate expired on %s.", certInfo.NotAfter),
		"Regenerate certificates by deleting the certs/ directory and restarting the sandbox.",
		"Alternatively, restart with the --ephemeral flag to generate fresh certs on every boot.",
	}
}

func notYetValidHints(certInfo *CertInfo) []string {
	return []string{
		fmt.Sprintf("Your certificate is not valid until %s.", certInfo.NotBefore),
		"Check that your system clock is set correctly.",
	}
}

func weakKeyHints(certInfo *CertInfo) []string {
	return []string{
		fmt.Sprintf("Your certificate uses a %s %d-bit key, which is below the minimum accepted strength.", certInfo.KeyType, certInfo.KeyBits),
		"Use RSA 2048+ or ECDSA P-256 (or stronger). Regenerate your key and certificate.",
	}
}

func noClientAuthHints() []string {
	return []string{
		"Your certificate does not include the ClientAuth extended key usage (EKU).",
		"This usually means a server certificate is being used as a client certificate by mistake.",
		"Issue a new certificate with ExtKeyUsage set to ClientAuth.",
	}
}

func noServerAuthHints() []string {
	return []string{
		"The server's certificate does not include the ServerAuth extended key usage (EKU).",
		"This usually means a client certificate is being used as the server certificate by mistake.",
		"Issue a new server certificate with ExtKeyUsage set to ServerAuth.",
	}
}
